PROJECT = make_release_example
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy
dep_cowboy_commit = 2.9.0
DEP_PLUGINS = cowboy #加载Cowboy提供的插件

LOCAL_DEPS = debugger

BUILD_DEPS += relx
include ../erlang.mk
