PROJECT = make_rel_example
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

LOCAL_DEPS = debugger
DEPS = recon bitcask redbug
dep_recon = hex 2.5.3
dep_bitcask = git https://github.com/basho/bitcask.git 2.1.0
dep_redbug = hex 2.0.7

BUILD_DEPS += relx
include ../erlang.mk
